StaffWebApp/StaffWebApp/Controllers/MessageCentreController.cs
using AutoMapper;
using MessageServiceFacadeProject;
using MessageServiceFacadeProject.DTOs;
using StaffWebApp.ViewModels.Messages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StaffWebApp.Controllers
{
    public class MessageCentreController : Controller
    {
        private IMapper iMapper;
        private AutoMapper.MapperConfiguration mapperConfig;
        private IMessageServiceFacade msFacade;

        public MessageCentreController(IMessageServiceFacade _msFacade)
        {
            msFacade = _msFacade;

            mapperConfig = new AutoMapper.MapperConfiguration(cfg =>
            {
                cfg.CreateMap<MS_Messages, MessageViewModel>();
            });
            iMapper = mapperConfig.CreateMapper();
        }


        // GET: MessageCentre
        [Authorize]
        public ActionResult Index()
        {
            IEnumerable<MS_Messages> messageList = msFacade.getMessagesFromSenderID(GetUserIdentity());
            if (messageList == null)
                return HttpNotFound();

            List<MessageViewModel> custMessageVM = messageList.Select(x => iMapper.Map<MS_Messages, MessageViewModel>(x)).ToList();

            return View(custMessageVM);
        }

        // GET: MessageCentre/Create
        [Authorize(Roles = "CanSendMessages")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: MessageCentre/Create
        [Authorize(Roles = "CanSendMessages")]
        [HttpPost]
        public ActionResult Create([Bind(Include = "Contents,RecipientString")] NewMessageViewModel newMessage)
        {
            if (newMessage != null && newMessage.RecipientString != null)
            {
                if (ModelState.IsValid)
                {
                    List<string> recipientList = newMessage.RecipientString.Split(';').ToList();
                    MS_SendMessageDTO newMessageDTO = new MS_SendMessageDTO()
                    {
                        SenderNo = GetUserIdentity(),
                        Contents = newMessage.Contents,
                        Recipients = recipientList
                    };
                    msFacade.sendMessageToRecipient(newMessageDTO);
                    return RedirectToAction("Index");
                }

                ModelState.AddModelError("", "Unable to send entered message, please try again.");
                return View(new NewMessageViewModel() { Contents = newMessage.Contents, RecipientString = newMessage.RecipientString });
            }
            return View( new NewMessageViewModel() );
        }

        private string GetUserIdentity()
        {
            if (User != null && User.Identity != null)
                return User.Identity.Name;
            return "P44_54"; //Test user
        }
    }
}

StaffWebApp/StaffWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ThAmCo Staff Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Stock", "Index", "Stock")</li>
                    <li>@Html.ActionLink("Customer", "Index", "Customer")</li>
                    <li>@Html.ActionLink("Invoices", "Index", "Invoices")</li>
                    <li>@Html.ActionLink("Message Centre", "Index", "MessageCentre")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>