StaffWebApp/StaffWebApp/ViewModels/Stock/PriceHistoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StaffWebApp.ViewModels.Stock
{
    public class PriceHistoryViewModel
    {
        [Display(Name = "Ean", Description = "Ean of the product.")]
        public string Ean { get; set; }
        [Display(Name = "Name", Description = "Name of the product.")]
        public string productName { get; set; }
        [Display(Name = "Price (£)", Description = "Historical price of the product.")]
        public double Price { get; set; }
        [Display(Name = "Date Changed", Description = "Date when price of the product was changed.")]
        public DateTime DateChanged { get; set; }
    }
}

StaffWebApp/StaffWebApp/ViewModels/Stock/WarehouseStockViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StaffWebApp.ViewModels.Stock
{
    public class WarehouseStockViewModel
    {
        public int ProductID { get; set; }
        [Display(Name = "Ean")]
        public string Ean { get; set; }
        [Display(Name = "Name", Description = "Name of the product")]
        public string ProductName { get; set; }
        [Display(Name = "Brand Name", Description = "Name of the product brand")]
        public string BrandName { get; set; }
        [Display(Name = "Category Name", Description = "Name of the product category")]
        public string CategoryName { get; set; }
        [Display(Name = "Description", Description = "A description of the product")]
        public string ProductDescription { get; set; }
        [Display(Name = "Price (£)", Description = "The price of the product")]
        public double Price { get; set; }
        [Display(Name = "Stock Level", Description = "The stock level of the product")]
        public int StockLevel { get; set; }
        [Display(Name = "Restock Warning Level")]
        public int RestockWarningLevel { get; set; }

        [System.Web.Mvc.HiddenInput(DisplayValue = false)]
        public bool RestockWarningBool { get { return StockLevel < RestockWarningLevel; } }
    }
}

StaffWebApp/StaffWebApp/Controllers/PurchaseStockController.cs
using CreditCardServiceFacadeProject;
using StaffWebApp.ViewModels.ThirdPartyStock;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ThirdPartyFacades;
using ThirdPartyFacades.BazzasBazaarService;
using ThirdPartyFacades.DTOs;
using ThirdPartyFacades.DTOs.UnderCutters;
using WarehouseServiceFacadeProject;

namespace StaffWebApp.Controllers
{
    public class PurchaseStockController : Controller
    {
        private IWarehouseServiceFacade whFacade;
        private ICreditCardServiceFacade ccFacade;

        public PurchaseStockController(IWarehouseServiceFacade _whFacade, ICreditCardServiceFacade _ccFacade, IUnderCutterFacade _ucFacade, IDodgyDealersFacade _ddFacade, IStore _bbStore)
        {
            whFacade = _whFacade;
            ccFacade = _ccFacade;
            ThirdPartyFacadeHandler.ucFacade = _ucFacade;
            ThirdPartyFacadeHandler.ddFacade = _ddFacade;
            //ThirdPartyFacadeHandler.bbFacade = _bbStore; //No test facade has been made for this service.
        }

        // GET: PurchaseStock
        [Authorize]
        public ActionResult Index(string tpService = "", string ean = "")
        {
            ViewBag.ThirdPartyServices = ThirdPartyFacadeHandler.returnViewBagList();
            ViewBag.ErrorMessage = "";
            IEnumerable<Combined_Product> returnedData = new List<Combined_Product>();

            if (tpService != null && tpService != "") //Filter by Service
            {
                returnedData = ThirdPartyFacadeHandler.getProducts(tpService);
                if (returnedData != null && returnedData.Count() <= 0)
                {
                    ViewBag.ErrorMessage = "We are unable to communicate with that service at the moment. Please try again later.";
                }
            }

            if (ean != null && ean != "") //Filter by EAN
            {
                if (tpService != null && tpService != "")
                    returnedData = returnedData.Where(x => x.Ean == ean);
            }

            if (returnedData.Count() > 0)
                return View(returnedData.Select(x => new ThirdPartyStockViewModel()
                {
                    Name = x.Name,
                    Ean = x.Ean,
                    Description = x.Description,
                    BrandName = x.BrandName,
                    ProductID = x.Id,
                    Price = x.PriceForOne,
                    CategoryName = x.CategoryName,
                    Provider = x.Provider
                }).ToList());

            return View(new List<ThirdPartyStockViewModel>());
        }

        // GET: PurchaseStock/Details/5
        [Authorize]
        public ActionResult Details(int? id, string tpService)
        {
            if (id == null || tpService == null || tpService == "")
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var detailedProduct = ThirdPartyFacadeHandler.getProductsByID(Int32.Parse(id.ToString()), tpService);
            if (detailedProduct == null)
                return HttpNotFound();

            return View(new ThirdPartyStockViewModel()
            {
                BrandName = detailedProduct.BrandName,
                CategoryName = detailedProduct.CategoryName,
                Description = detailedProduct.Description,
                Ean = detailedProduct.Ean,
                Name = detailedProduct.Name,
                Price = detailedProduct.PriceForOne,
                ProductID = detailedProduct.Id,
                Provider = detailedProduct.Provider
            });
        }

        // GET: PurchaseStock/PlaceOrder/5
        [Authorize(Roles = "CanPurchaseFromThirdParty")]
        public ActionResult PlaceOrder(int? id, string tpService)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var detailedProduct = ThirdPartyFacadeHandler.getProductsByID(Int32.Parse(id.ToString()), tpService);
            if (detailedProduct == null)
                return HttpNotFound();

            return View(new ThirdPartyOrderStockViewModel()
            {
                Name = detailedProduct.Name,
                Description = detailedProduct.Description,
                BrandName = detailedProduct.BrandName,
                CategoryName = detailedProduct.CategoryName,
                Ean = detailedProduct.Ean,
                Price = detailedProduct.PriceForOne,
                PricePer10 = detailedProduct.PriceForTen,
                ProductID = detailedProduct.Id,
                Seller = tpService,
                CreditCards = ccFacade.getCreditCards()
            });


        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "CanPurchaseFromThirdParty")]
        public ActionResult PlaceOrder([Bind(Include = "Name,Description,BrandName,CategoryName,Ean,Price,PricePer10,ProductID,Seller,Quantity,SelectedCreditCardNumber")] ThirdPartyOrderStockViewModel orderVM)
        {
            if (ModelState.IsValid && orderVM != null)
            {
                var cardObj = ccFacade.getCreditCards().Where(x => x.hashCard == orderVM.SelectedCreditCardNumber).FirstOrDefault();
                if (cardObj != null)
                {
                    try
                    {
                        bool placed = ThirdPartyFacadeHandler.placeOrder(new Combined_Order()
                        {
                            ProductId = orderVM.ProductID,
                            AccountName = cardObj.nameOnCard,
                            CardNumber = cardObj.rawCardNumber,
                            Quantity = orderVM.Quantity,
                        }, orderVM.Seller);

                        if (placed)
                        {
                            List<WarehouseServiceFacadeProject.DTOs.WH_ProductStockUpdate> newStockItem = new List<WarehouseServiceFacadeProject.DTOs.WH_ProductStockUpdate>()
                            {
                                new WarehouseServiceFacadeProject.DTOs.WH_ProductStockUpdate()
                                {
                                    ProductName = orderVM.Name,
                                    ProductDescription = orderVM.Description,
                                    BrandName = orderVM.BrandName,
                                    CategoryName = orderVM.CategoryName,
                                    Ean = orderVM.Ean,
                                    StockToAdd = orderVM.Quantity,
                                    Price = orderVM.Price
                                },
                            };
                            whFacade.addProductStock(newStockItem);
                            return RedirectToAction("Index", new { tpService = orderVM.Seller, ean = orderVM.Ean });
                        }
                    }
                    catch (Exception ex) { } // Try catch to catch expection thrown manually.
                }
            }
            return View(orderVM);
        }
    }
}

StaffWebApp/StaffWebApp/Controllers/StockController.cs
using AutoMapper;
using StaffWebApp.ViewModels.Stock;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WarehouseServiceFacadeProject;
using WarehouseServiceFacadeProject.DTOs;

namespace StaffWebApp.Controllers
{
    [Authorize(Roles = "Staff")]
    /// <summary>
    /// Stock Controller. Contains methods to retrieve stock details from facades and construct them into viewmodels to be passed to the current stock pages.
    /// </summary>
    public class StockController : Controller
    {
        /// <summary>
        /// The Warehouse facade. Contains methods to retrieve warehouse data from the WarehouseService.
        /// </summary>
        private readonly IWarehouseServiceFacade whFacade;

        /// <summary>
        /// The AutoMapper object. Used to map objects from one type to another.
        /// </summary>
        private IMapper iMapper;

        /// <summary>
        /// The AutoMapper config. Defines what objects can be mapped into what other objects.
        /// </summary>
        private AutoMapper.MapperConfiguration mapperConfig;

        public StockController(IWarehouseServiceFacade _whFacade)
        {
            whFacade = _whFacade;
            mapperConfig = new AutoMapper.MapperConfiguration(cfg =>
            {
                cfg.CreateMap<WH_Product, WarehouseStockViewModel>();
                cfg.CreateMap<WH_PriceHistory, PriceHistoryViewModel>();
                cfg.CreateMap<WarehouseStockViewModel, WH_ProductPriceUpdate>();
            });
            iMapper = mapperConfig.CreateMapper();
        }

        #region CurrentStockPage
        // GET: Stock
        [Authorize(Roles= "CanViewStockLevel")]
        public ActionResult Index()
        {
            List<ViewModels.Stock.WarehouseStockViewModel> warehouseVMs = new List<ViewModels.Stock.WarehouseStockViewModel>();
            var productsList = whFacade.getProducts();
            if (productsList != null && productsList.Count() > 0)
                warehouseVMs = productsList.Select(x => iMapper.Map<WH_Product, ViewModels.Stock.WarehouseStockViewModel>(x)).ToList();

            return View(warehouseVMs);
        }

        // GET: Stock/Edit/5
        [Authorize(Roles = "CanEditProducts")]
        public ActionResult Edit(string ean = "")
        {
            if (ean == null || ean == "")
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            WH_Product product = whFacade.getProductByEAN(ean);
            if (product == null)
                return HttpNotFound();

            return View(iMapper.Map<WH_Product, WarehouseStockViewModel>(product));
        }

        [HttpPost]
        [Authorize(Roles = "CanEditProducts")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,Ean,ProductName,BrandName,CategoryName,ProductDescription,Price,StockLevel,RestockWarningLevel")] WarehouseStockViewModel stockVM)
        {
            if (ModelState.IsValid && stockVM != null)
            {
                var editedProduct = iMapper.Map<WarehouseStockViewModel, WH_ProductPriceUpdate>(stockVM);
                var successful = whFacade.editProduct(editedProduct);
                if(successful)
                    return RedirectToAction("Index");
                else
                    ModelState.AddModelError("", "Unable to edit that product at the moment, please try again later.");
            }
            return View(stockVM);
        }

        [Authorize(Roles = "CanViewProductPriceHistory")]
        public ActionResult PriceHistory(string ean = "")
        {
            if(ean == null || ean == "")
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            IEnumerable<WH_PriceHistory> product = whFacade.getPriceHistoryByEAN(ean);
            if (product == null)
                return HttpNotFound();

            List<PriceHistoryViewModel> vmList = product.Select(x => iMapper.Map<WH_PriceHistory, PriceHistoryViewModel>(x)).ToList();
            return View(vmList);
        }
        #endregion
    }
}

StaffWebApp/StaffWebApp/Views/Stock/Edit.cshtml
@model StaffWebApp.ViewModels.Stock.WarehouseStockViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ean, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Ean, new { @class = "form-control", @readonly = "readonly", style = "width: 450px;" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ProductName, new { @class = "form-control", @readonly = "readonly", style = "width: 450px;" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrandName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.BrandName, new { @class = "form-control", @readonly = "readonly", style = "width: 450px;" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.CategoryName, new { @class = "form-control", @readonly = "readonly", style = "width: 450px;" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductDescription, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ProductDescription, new { @class = "form-control", @readonly = "readonly", style = "width: 450px;" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StockLevel, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.StockLevel, new { @class = "form-control", @readonly = "readonly", style = "width: 450px;" })
            </div>
        </div>

        <br />
        <h3>Editable Details</h3>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Price)
                    @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RestockWarningLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.RestockWarningLevel)
                    @Html.ValidationMessageFor(model => model.RestockWarningLevel, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Price History", "PriceHistory", new { ean = Model.Ean }) |
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StaffWebApp/StaffWebApp/Views/Stock/Index.cshtml
@model IEnumerable<StaffWebApp.ViewModels.Stock.WarehouseStockViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Stock Level Page</h2>
<br/>
<p>
    @Html.ActionLink("Purchase Stock", "Index", "PurchaseStock")
</p>

<br/>
<h3>Stock Level Warning</h3>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ean)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BrandName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StockLevel)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Where(x => x.RestockWarningBool))
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ean)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BrandName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StockLevel)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  ean=item.Ean }) |
                @Html.ActionLink("Restock", "Index", "PurchaseStock", new { tpService = "", ean = item.Ean }, "")
            </td>
        </tr>
    }

</table>

<br/>
<h3>Stock Levels</h3>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ean)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BrandName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StockLevel)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.Where(x => !x.RestockWarningBool)) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ean)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BrandName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StockLevel)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { ean = item.Ean }) |
            @Html.ActionLink("Restock", "Index", "PurchaseStock", new { tpService = "", ean = item.Ean }, "")
        </td>
    </tr>
}

</table>

StaffWebApp/StaffWebApp/Views/Stock/PriceHistory.cshtml
@model IEnumerable<StaffWebApp.ViewModels.Stock.PriceHistoryViewModel>

@{
    ViewBag.Title = "PriceHistory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Price History</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ean)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.productName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateChanged)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ean)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.productName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateChanged)
        </td>
    </tr>
}

</table>
<p>
    @Html.ActionLink("Back to Editing", "Edit", new { ean = Model.FirstOrDefault().Ean })
</p>