StaffWebApp/StaffWebApp/Controllers/UserLoginController.cs
using StaffProfileServiceFacadeProject;
using StaffProfileServiceFacadeProject.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace StaffWebApp.Controllers
{
    public class UserLoginController : Controller
    {
        private IStaffProfileServiceFacade spFacade;
        private IUserLoginWrapper usLogin;

        public UserLoginController(IStaffProfileServiceFacade _spFacade, IUserLoginWrapper _usLogin)
        {
            spFacade = _spFacade;
            usLogin = _usLogin;
        }

        // GET: UserLogin
        public ActionResult Index()
        {
            return View();
        }

        //[HttpGet]
        //public ActionResult Register()
        //{
        //    return View();
        //}

        //[HttpPost]
        //[AllowAnonymous]
        //[ValidateAntiForgeryToken]
        //public ActionResult Register(ViewModels.Account.AccountRegister user)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var staffProfile = spFacade.getStaffProfileFromLogin(user.Email);
        //        if(staffProfile == null)
        //        {
        //            spFacade.registerNewStaff(new StaffProfileServiceFacadeProject.DTOs.SP_StaffProfile()
        //            {
        //                Email = user.Email,
        //                PasswordHash = SHA1.Encode(user.Password),
        //            });

        //            return RedirectToAction("Index", "Home");
        //        }
        //        else
        //        {
        //            ModelState.AddModelError("", "That email is already in use, please try another.");
        //        }
        //    }
        //    return View(user);
        //}

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(ViewModels.Account.AccountLogin user)
        {     
            if (ModelState.IsValid && user != null)
            {
                var staffProfile = spFacade.getStaffProfileFromLogin(new SP_StaffLoginDTO() {Username = user.Username, Password = SHA1.Encode(user.Password) });
                if (staffProfile != null)
                {
                    if (usLogin.AuthenticateUser(user.Username, user.RememberMe) && usLogin.GenerateCookies(staffProfile, spFacade))
                        return RedirectToAction("Index", "Home");
                    else
                        Logout(); //Authentication may have passed but cookie generation did not, in that case we want to logout user to prevent issues.
                }
                else
                {
                    ModelState.AddModelError("", "Login data is incorrect!");
                }
            }
            return View(user);
        }

        public ActionResult Logout()
        {
            usLogin.SignOutUser();
            return RedirectToAction("Index", "Home");
        }
    }
}

StaffWebApp/StaffWebApp/Views/UserLogin/Login.cshtml
@model StaffWebApp.ViewModels.Account.AccountLogin
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "UserLogin", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>Use a local account to log in.</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.Username, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Username, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.RememberMe)
                            @Html.LabelFor(m => m.RememberMe)
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                /*<p>
                    @Html.ActionLink("Register as a new user", "Register")
                </p>*/
                @* Enable this once you have account confirmation enabled for password reset functionality
                    <p>
                        @Html.ActionLink("Forgot your password?", "ForgotPassword")
                    </p>*@
            }
        </section>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StaffWebApp/StaffWebApp/Views/UserLogin/Register.cshtml
@model StaffWebApp.ViewModels.Account.AccountRegister
@{
    ViewBag.Title = "Register";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("Register", "UserLogin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Create a new account.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Username, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Username, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Register" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}